/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FellowshipRouteImport } from './routes/fellowship'
import { Route as WorshipRouteImport } from './routes/worship'
import { Route as SermonsIndexRouteImport } from './routes/sermons/index'
import { Route as SermonsIdRouteImport } from './routes/sermons/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FellowshipRoute = FellowshipRouteImport.update({
  id: '/fellowship',
  path: '/fellowship',
  getParentRoute: () => rootRouteImport,
} as any)
const WorshipRoute = WorshipRouteImport.update({
  id: '/worship',
  path: '/worship',
  getParentRoute: () => rootRouteImport,
} as any)
const SermonsIndexRoute = SermonsIndexRouteImport.update({
  id: '/sermons/',
  path: '/sermons/',
  getParentRoute: () => rootRouteImport,
} as any)
const SermonsIdRoute = SermonsIdRouteImport.update({
  id: '/sermons/$id',
  path: '/sermons/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fellowship': typeof FellowshipRoute
  '/worship': typeof WorshipRoute
  '/sermons/$id': typeof SermonsIdRoute
  '/sermons/': typeof SermonsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fellowship': typeof FellowshipRoute
  '/worship': typeof WorshipRoute
  '/sermons/$id': typeof SermonsIdRoute
  '/sermons': typeof SermonsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fellowship': typeof FellowshipRoute
  '/worship': typeof WorshipRoute
  '/sermons/$id': typeof SermonsIdRoute
  '/sermons/': typeof SermonsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/fellowship' | '/worship' | '/sermons/$id' | '/sermons/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/fellowship' | '/worship' | '/sermons/$id' | '/sermons'
  id:
    '__root__' | '/' | '/fellowship' | '/worship' | '/sermons/$id' | '/sermons/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FellowshipRoute: typeof FellowshipRoute
  WorshipRoute: typeof WorshipRoute
  SermonsIdRoute: typeof SermonsIdRoute
  SermonsIndexRoute: typeof SermonsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fellowship': {
      id: '/fellowship'
      path: '/fellowship'
      fullPath: '/fellowship'
      preLoaderRoute: typeof FellowshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worship': {
      id: '/worship'
      path: '/worship'
      fullPath: '/worship'
      preLoaderRoute: typeof WorshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sermons/': {
      id: '/sermons/'
      path: '/sermons'
      fullPath: '/sermons/'
      preLoaderRoute: typeof SermonsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sermons/$id': {
      id: '/sermons/$id'
      path: '/sermons/$id'
      fullPath: '/sermons/$id'
      preLoaderRoute: typeof SermonsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FellowshipRoute: FellowshipRoute,
  WorshipRoute: WorshipRoute,
  SermonsIdRoute: SermonsIdRoute,
  SermonsIndexRoute: SermonsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
